# source 'https://github.com/spotii-me/ios-framework-podspecs.git'

# folly_compiler_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -Wno-comma -Wno-shorten-64-to-32'

# # require_relative '../node_modules/react-native/scripts/react_native_pods'
# # require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '14.0'
# # prepare_react_native_project!

# # If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# # because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
# #
# # To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# # ```js
# # module.exports = {
# #   dependencies: {
# #     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# # ```
# # flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# # linkage = ENV['USE_FRAMEWORKS']
# # if linkage != nil
# #   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
# #   use_frameworks! :linkage => linkage.to_sym
# # end

# target 'ios-sdk-poc' do
#   use_frameworks! :linkage => :static

#   pod 'boost'
#   pod 'DoubleConversion'
#   pod 'FBLazyVector'
#   pod 'FBReactNativeSpec'
#   pod 'glog'
#   pod 'hermes-engine'
#   pod 'RCT-Folly'
#   pod 'RCTRequired'
#   pod 'RCTTypeSafety'
#   pod 'React'
#   pod 'React-callinvoker'
#   pod 'React-Codegen'
#   pod 'React-Core'
#   pod 'React-CoreModules'
#   pod 'React-cxxreact'
#   pod 'React-hermes'
#   pod 'React-jsi'
#   pod 'React-jsiexecutor'
#   pod 'React-jsinspector'
#   pod 'React-logger'
#   pod 'React-perflogger'
#   pod 'React-RCTActionSheet'
#   pod 'React-RCTAnimation'
#   pod 'React-RCTAppDelegate'
#   pod 'React-RCTBlob'
#   pod 'React-RCTImage'
#   pod 'React-RCTLinking'
#   pod 'React-RCTNetwork'
#   pod 'React-RCTSettings'
#   pod 'React-RCTText'
#   pod 'React-RCTVibration'
#   pod 'React-runtimeexecutor'
#   pod 'ReactCommon'
#   pod 'Yoga', :source => 'https://github.com/spotii-me/ios-framework-podspecs.git'

#   target 'ios-sdk-pocTests' do
#     inherit! :complete
#     # Pods for testing
#   end

#   # post_install do |installer|
#   #   react_native_post_install(
#   #     installer,
#   #     # Set `mac_catalyst_enabled` to `true` in order to apply patches
#   #     # necessary for Mac Catalyst builds
#   #     :mac_catalyst_enabled => false
#   #   )
#   #   __apply_Xcode_12_5_M1_post_install_workaround(installer)
#   # end
# end

# source 'https://github.com/CocoaPods/Specs.git'
# source 'https://github.com/spotii-me/ios-framework-podspecs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ios-sdk-poc' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ios-sdk-pocTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
